# Generated by Django 4.1.7 on 2023-03-29 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_mymodel_alter_comment_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='create_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 9, 48, 53, 535109, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 9, 48, 53, 535109, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 29, 9, 48, 53, 535109, tzinfo=datetime.timezone.utc)),
        ),
    ]
